name: Playwright Tests

on:
  push:
    branches: [main]

jobs:
  playwrighttests:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.52.0
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Start backend server
        run: |
          chmod +x ./shopping-store-linux-amd64
          nohup ./shopping-store-linux-amd64 > server.log 2>&1 &
          sleep 5
          curl -i http://localhost:2221 || true

      - name: Run Playwright tests
        run: npm run test:ci

      - name: Show backend logs
        if: failure()
        run: cat server.log
